name: SonarQube Scan

on:
  push:
    branches:
      - master

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Debug SONAR_HOST_URL
        run: echo $SONAR_HOST_URL
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Run SonarQube Scanner
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_LOGIN: ${{ secrets.SONAR_TOKEN }}
        run: |
          docker run --rm \
          -e SONAR_HOST_URL=$SONAR_HOST_URL \
          -e SONAR_LOGIN=$SONAR_LOGIN \
          -v $(pwd):/usr/src \
          sonarsource/sonar-scanner-cli \
          sonar-scanner \
            -Dsonar.projectKey=MethawiPhokhai_DapperCRUDApplication \
            -Dsonar.sources=. \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_LOGIN