name: SonarQube Scan

on:
  push:
    branches:
      - master

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run SonarQube Scanner
        run: |
          docker run --rm \
          -e SONAR_HOST_URL=$SONAR_HOST_URL \
          -e SONAR_LOGIN=$SONAR_LOGIN \
          -v $(pwd):/usr/src \
          sonarsource/sonar-scanner-cli \
          sonar-scanner \
            -Dsonar.projectKey=MethawiPhokhai_DapperCRUDApplication \
            -Dsonar.sources=. \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}